# Generated by Django 4.0.5 on 2022-08-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('cuerpo', models.CharField(max_length=10000)),
                ('imagen', models.ImageField(upload_to='')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
