# Generated by Django 4.0.5 on 2022-08-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0003_alter_receta_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
