# Generated by Django 4.0.5 on 2022-07-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formulario',
            new_name='Socio',
        ),
    ]
