# Generated by Django 4.0.5 on 2022-08-11 18:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0002_remove_receta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
